### ISSUE TITLE
[Dúvida] Junção natural

### ISSUE THREAD

**Issue by Murilomsq** [plinioleitao/bd-2021-1-bia#289]
Se em algum momento eu quiser realizar uma junção comparando dois atributos que tem nomes diferentes nas relações utilizadas, é melhor eu realizar uma equijunção (por exemplo TRABALHA_EM⋈Fcpf= CpfFUNCIONARIO) ou mudar o nome de um dos atributos em uma relação auxiliar e fazer uma junção natural? (Quanto ao custo computacional e a praticidadde)

**Comment by plinioleitao** [comment]
Obrigado pela pergunta.
Penso que não há diferença em relação ao 'custo computacional'.
Em relação à 'praticidade', trata-se de escolha de estilo de programação e/ou padrão adotado na empresa. Penso que o predicado explícito (em vez de junção natural) promove a legibilidade e o entendimento da consulta.
