### ISSUE TITLE
[Dúvida] Banco de dados empresa para usar no RELAX

### ISSUE THREAD

**Issue by aveusalex** [plinioleitao/bd-2021-1-bia#340]
Conforme foi solicitado, deixo aqui o banco de dados "Empresa" para poder ser usado no RELAX.

Link: https://github.com/aveusalex/BD_empresa

**Comment by aveusalex** [comment]
Finalizado as alterações solicitadas em aula. 
Adicionei o passo a passo de como utilizar o BD, está no readme.md do repositório.

**Comment by plinioleitao** [comment]
Obrigado Alex.
