### ISSUE TITLE
[Dúvida] Junção natural externa

### ISSUE THREAD

**Issue by Murilomsq** [plinioleitao/bd-2021-1-bia#406]
Para o caso de duas relações terem atributos a serem comparados com o mesmo nome, existe algum operador pra representar uma junção natural externa? Por exemplo, temos que:

`RELACAO1 * RELAÇÃO2 ≡ RELACAO1 ⨝distancia = distancia RELAÇÃO1`
 **_(no caso de existir somente a "distancia" como atributo com o mesmo nome entre as relações 1 e 2)_** 

Existe algum operador pra substituir o "?"
`RELACAO1 ? RELAÇÃO2 ≡ RELACAO1 ⟕distancia = distancia RELAÇÃO1`

**Comment by plinioleitao** [comment]
Oi Murilo, na álgebra relacional original (escopo da nossa disciplina), penso que não há a noção de "junção natural externa".
Vale ressaltar que nesse caso é necessário 'qualificar' o atributo; por exemplo, "RELACAO1.distancia = RELACAO2.distancia".
