### ISSUE TITLE
[Dúvida] Sintaxe SQL

### ISSUE THREAD

**Issue by aveusalex** [plinioleitao/bd-2021-1-bia#443]
Na operação natural join, no Maria DB, percebi que quando eu tentei realizar o natural join da seguinte operação:

SELECT Pnome, Unome, Endereco
FROM FUNCIONARIO NATURAL JOIN 
( SELECT Dnumero as Dnr From DEPARTAMENTO ) 

Percebi que retornava erro. Achei que era algum erro com o nome dos atributos. Modifiquei varias vezes e nada. 
Daí, coloquei depois dos parênteses "AS DPTO" e funcionou. Por que isso acontece?

**Comment by plinioleitao** [comment]
É necessário usar 'AS <alias>' em subconsultas presentes na cláusula FROM, penso que se refere: ao processamento da consulta em si (o SGBD constrói uma 'árvore de execução' em que as relações estão 'nomeadas'), e à potencial (possível) necessidade de qualificação (desambiguação) de atributos.
