### ISSUE TITLE
[Dúvida] Ingenuidade com SQL

### ISSUE THREAD

**Issue by aveusalex** [plinioleitao/bd-2021-1-bia#444]
Maria DB ainda.

Por que o seguinte comando retorna erro sempre?

SELECT Pnome, Unome, Dnome, projnome
FROM FUNCIONARIO 
JOIN (SELECT Dnumero, Dnome from DEPARTAMENTO) ON Dnr=Dnumero
JOIN (SELECT Projnome, Dnum FROM PROJETO) ON Dnr=Dnumero

**Comment by plinioleitao** [comment]
Tente o comando abaixo:
SELECT Pnome, Unome, Dnome, projnome
FROM FUNCIONARIO
     JOIN (SELECT Dnumero, Dnome from DEPARTAMENTO) AS DEPTO ON Dnr=Dnumero
     JOIN (SELECT Projnome, Dnum FROM PROJETO) AS PROJ ON Dnr=Dnumero
