### ISSUE TITLE
Tópico 18

### ISSUE THREAD

**Issue by accorado** [plinioleitao/bd-2021-1-bia#567]
01. Qual a soma dos salários que são retornados pela consulta?
A soma é 55000.

02. Some as sentenças verdadeiras.
04 + 08 + 16 + 32 = 60.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.

**Comment by plinioleitao** [comment]
Você respondeu na turma do Bacharelado em Inteligência Artificial.
Sua turma é do Bacharelado em Ciência da Computação.
SEM APROVEITAMENTO.
