### ISSUE TITLE
Tópico 19

### ISSUE THREAD

**Issue by accorado** [plinioleitao/bd-2021-1-bia#569]
SELECT Primnome, Ultnome
FROM FUNCIONARIO JOIN DEPENDENTE
ON Cpf = Fcpf
GROUP BY Primnome, Ultnome
HAVING COUNT(Cpf) >= 2
INTERSECT
SELECT Primnome, Ultnome
FROM FUNCIONARIO JOIN TRABALHA_EM
ON Cpf = Fcpf
GROUP BY Primnome, Ultnome
HAVING COUNT(Cpf) >= 2

**Comment by plinioleitao** [comment]
Há os atribtutos Primnome, Ultnome ?
Se houver funcionários homônimos?
SEM APROVEITAMENTO.

Favor responder a partir do portal da sua turma (https://github.com/plinioleitao/bd-2021-1-bcc).
