### ISSUE TITLE
Dúvida em relação ao aproveitamento do tópico 24 

### ISSUE THREAD

**Issue by aveusalex** [plinioleitao/bd-2021-1-bia#785]
Professor, boa noite. Não entendi o porquê de ficar sem aproveitamento referente ao tópico 24. O senhor disse que ia considerar alguns erros. Gostaria de entender. Muito obrigado!

https://github.com/aveusalex/bd-2021-1-bia/blob/main/topico-24/Diagrama3.jpeg

**Comment by plinioleitao** [comment]
Por favor, veja a resposta no Tópico 24, para então comparar com a sua resposta.
O tipo de entidade fraca possui um único tipo de entidade proprietária, que é CLIENTE (não inclui MOTORISTA).
