### ISSUE TITLE
Tópico <03>

### ISSUE THREAD

**Issue by Rod15greo** [plinioleitao/bd-2021-1-bia#86]
**1- Markup Language:**
A linguagem de marcação é uma linguagem de computador usada para esclarecer o conteúdo de um documento. Tem como objetivo processar, definir e apresentar texto de computador de uma forma que os humanos possam ler. Ele especifica o código usado para formatar o texto, incluindo o estilo e o layout que o programador deseja que o documento exiba. Ele usa tags para definir esses elementos.
**Exemplo:**
**HTML**
É a linguagem de marcação mais amplamente usada hoje. É usado principalmente para desenvolver as páginas da web que vemos na internet. Em essência, cada página da web pode ser escrita em uma versão HTML. Isso torna o código essencial para garantir que o texto e as imagens no site sigam o formato correto. Sem ele, o navegador não saberá como exibir o conteúdo. O HTML também é responsável por fornecer a estrutura básica das páginas da web. 
**XML**
Bem semelhante ao HTML. O eXtensible Markup Language (XML) permite que o navegador exiba e leia as informações de forma correta. Porém o XML é extensível. Ele permite que as tags se caracterizem com base em uma descrição específica das informações, em vez de apenas exibi-lo.

- https://techterms.com/definition/markup_language
- https://en.wikipedia.org/wiki/Markup_language
- https://www.techopedia.com/definition/2668/markup-language

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
